import { ArrowRight, BarChart3, Banknote, CalendarCheck, Check, CheckCircle2, Clock3, FileCheck2, Globe2, Leaf, Mail, MapPin, Phone, ShieldCheck, Sprout, Store, Users } from 'lucide-react'
import './AudiencePage.css'

type Icon = typeof Leaf
type Config = { label: string; title: string; highlight: string; intro: string; icon: Icon; tone: string; heroImage: string; bullets: { title: string; text: string; icon: Icon }[]; sectionTitle: string; cards: { title: string; text: string; icon: Icon }[] }
const farmerImage = 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYUselL-PQVbZUGZKw0xjV5xKI7uRUs4do7e-XN3k_7jqISqdVcS09TUGq680M7mYfx0zb-wWX2UQcPyzybepBKUyH1HcQXzYuvbILiCbkcTMcldLloAyXNx7b4_IPITAN5qDiAybrWeAAUznW9QJl0AHPkQLii5wooxjvKd_0ENqPB9xe82UW6gFtP-nu8zZSB1AssfNFQ9f2pGjaePme1cX7gbGhGzfJp4fnYkKWsnoXERQSxuLW'
const centreImage = 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6UVp7bxXEuGfrIBtmrW6NBK00TD66-dRyBetAWCGstXWZSxxpAOZIV5SOE12KWy2Ta0AN1zT-RC-PLxFr45cyi4I2Y7RgRQUsga6c7wgy24s7pIJgQ1tNmXpmoY7gkjaEl6TuIr6fB7BVB-ECLH18RvU_2ydXxZwt5fff5GOy-syrkWbsJ_jtGWgUdzR5-EjLtCjTPbgDrrhooe_LK2sWAnvcGEqa0QG-45ziJYGr_DUYTXhhy7Ne'
const featureImage = farmerImage
const configs: Record<string, Config> = {
  '/for-farmers': { label: 'For Farmers', title: 'Empowering Farmers.', highlight: 'Enriching Futures', intro: 'Kisan Setu is built to empower farmers by giving them easy access to procurement centres, real-time updates, fair prices and secure payments.', icon: Users, tone: 'green', heroImage: farmerImage, bullets: [{ title: 'Mobile Friendly', text: 'Use on any smartphone, anytime, anywhere.', icon: Globe2 }, { title: 'Multi-language Support', text: 'Available in multiple regional languages.', icon: Globe2 }, { title: 'No Registration Hassle', text: 'Quick & simple registration process.', icon: CheckCircle2 }, { title: 'Help When You Need It', text: 'Get support via helpline, WhatsApp & email.', icon: Phone }], sectionTitle: 'Benefits for Farmers', cards: [{ title: 'Book Slots Easily', text: 'Find nearby procurement centres and book your slot in advance.', icon: CalendarCheck }, { title: 'Live Queue Tracking', text: 'Track live queue status and estimated waiting time.', icon: Users }, { title: 'Fair & Transparent', text: 'Enjoy a transparent process with quality checks and fair weighing.', icon: ShieldCheck }, { title: 'Secure Payments', text: 'Get paid directly to your bank account quickly and securely.', icon: Banknote }, { title: 'History & Records', text: 'Access procurement history, payments and receipts anytime.', icon: FileCheck2 }] },
  '/for-centres': { label: 'For Procurement Centres', title: 'Digitize. Organize.', highlight: 'Serve Better.', intro: 'Kisan Setu empowers procurement centres with smart tools to manage slots, track produce, ensure quality, and maintain transparency in every transaction.', icon: Store, tone: 'blue', heroImage: centreImage, bullets: [{ title: 'Efficient Centre Management', text: 'Manage slots, farmers and daily operations.', icon: Store }, { title: 'Real-time Queue & Slot Control', text: 'Monitor crowd flow and service status.', icon: Clock3 }, { title: 'Quality & Weight Verification', text: 'Record quality and weighment accurately.', icon: ShieldCheck }, { title: 'Transparent & Secure Operations', text: 'Keep every record clear and auditable.', icon: FileCheck2 }], sectionTitle: 'Powerful Features for Centres', cards: [{ title: 'Slot Management', text: 'Create, update and manage daily procurement slots effortlessly.', icon: CalendarCheck }, { title: 'Live Queue View', text: 'Monitor live queue, estimated wait times and crowd flow.', icon: Users }, { title: 'Quality Assurance', text: 'Digital quality checks and weighment ensure fair procurement.', icon: ShieldCheck }, { title: 'Digital Weighment', text: 'Accurate weighment integration for transparency and trust.', icon: FileCheck2 }, { title: 'Instant Payments', text: 'Farmers get paid directly in their bank accounts.', icon: Banknote }, { title: 'Data & Reports', text: 'Generate detailed reports and download records anytime.', icon: BarChart3 }] },
  '/features': { label: 'Our Powerful Features', title: 'Powerful Features,', highlight: 'Smarter Procurement', intro: 'Kisan Setu is packed with smart features that make agricultural procurement simple, transparent, and efficient for everyone involved in the ecosystem.', icon: Sprout, tone: 'violet', heroImage: featureImage, bullets: [{ title: 'Farmer Friendly', text: 'Simple tools for every farmer.', icon: Users }, { title: 'Centre Efficient', text: 'Powerful operational controls.', icon: Store }, { title: 'Admin Insights', text: 'Data-driven decisions at scale.', icon: BarChart3 }, { title: 'Secure & Transparent', text: 'Built on trust and accountability.', icon: ShieldCheck }], sectionTitle: 'Features Built for Every User', cards: [{ title: 'For Farmers', text: 'Simple tools that help farmers save time, get fair value, and track everything easily.', icon: Users }, { title: 'For Centres', text: 'Powerful management tools to handle slots, farmers, and procurement smoothly.', icon: Store }, { title: 'For Administrators', text: 'Advanced analytics and controls to ensure transparency and better decision making.', icon: BarChart3 }] },
}
const contactDetails: [string, string, string, Icon][] = [
  ['Call Us', '1800-123-4567', 'Toll Free (8:00 AM - 8:00 PM)', Phone], ['Email Us', 'support@kisansetu.gov.in', 'We reply within 24 working hours', Mail],
  ['Working Hours', 'Monday - Saturday', '8:00 AM - 8:00 PM', Clock3], ['Head Office', 'Department of Agriculture, Krishi Bhawan, New Delhi - 110001', '', MapPin],
]
export default function AudiencePage({ path }: { path: string }) {
  if (path === '/contact') return <ContactPage />
  const config = configs[path] ?? configs['/for-farmers']; const HeroIcon = config.icon
  return <div className={`audience-page ${config.tone}`}><PublicHeader active={config.label} /><main><section className="audience-hero"><div className="audience-copy"><span className="audience-kicker"><HeroIcon size={14} /> {config.label}</span><h1>{config.title}<br /><em>{config.highlight}</em></h1><p>{config.intro}</p><div className="audience-bullets">{config.bullets.map(({ title, text, icon: BulletIcon }) => <div key={title}><span><BulletIcon size={14} /></span><strong>{title}</strong><small>{text}</small></div>)}</div><a className="audience-cta" href="/farmer/dashboard">Book Your Slot <ArrowRight size={16} /></a></div><div className="audience-image" style={{ backgroundImage: `url(${config.heroImage})` }} /><div className="audience-note"><h2>Why {config.label} choose Kisan Setu?</h2>{config.bullets.slice(0, 5).map(({ title }) => <p key={title}><Check size={14} />{title}</p>)}</div></section><section className="audience-section"><SectionHeading title={config.sectionTitle} /><div className="audience-cards">{config.cards.map((card) => card.title === 'Data & Reports' ? <ReportCard key={card.title} /> : <article key={card.title}><span><card.icon size={19} /></span><h3>{card.title}</h3><p>{card.text}</p></article>)}</div></section><section className="audience-journey"><SectionHeading title={path === '/features' ? 'One Platform. Every User.' : 'How You Benefit at Every Step'} /><div className="journey-line">{['Discover', 'Book', 'Track', 'Process', 'Get Paid', 'View Records'].map((step, index) => <div key={step}><b>{index + 1}</b><span><CheckCircle2 size={18} /></span><strong>{step}</strong><small>Simple and transparent</small></div>)}</div></section></main><PublicFooter /></div>
}
function ReportCard() { return <article className="report-card"><div className="report-card-header"><span><BarChart3 size={19} /></span><div><h3>Data & Reports</h3><p>Turn centre activity into clear decisions.</p></div><span className="report-live">Live</span></div><div className="report-kpis"><div><strong>1,256</strong><small>Appointments</small></div><div><strong>92%</strong><small>Utilization</small></div><div><strong>4.8h</strong><small>Avg. wait</small></div></div><div className="report-chart" aria-label="Weekly procurement trend"><span style={{ height: '42%' }} /><span style={{ height: '60%' }} /><span style={{ height: '48%' }} /><span style={{ height: '78%' }} /><span style={{ height: '68%' }} /><span style={{ height: '92%' }} /><span style={{ height: '81%' }} /></div><div className="report-footer"><small>Weekly centre performance</small><button>View reports <ArrowRight size={14} /></button></div></article> }
function ContactPage() { return <div className="audience-page contact-page"><PublicHeader active="Contact Us" /><main><section className="contact-hero"><div><span className="audience-kicker"><Phone size={14} /> We're Here to Help</span><h1>Contact Us</h1><p>Have questions, suggestions, or need support? We're just a message away. Reach out to us and we'll get back to you as soon as possible.</p><strong><Phone size={17} /> Dedicated support for farmers & procurement centres</strong></div><div className="contact-map"><MapPin size={34} /><span>New Delhi</span></div></section><section className="contact-details">{contactDetails.map(([title, value, text, DetailIcon]) => <article key={title}><span><DetailIcon size={20} /></span><div><h3>{title}</h3><strong>{value}</strong><p>{text}</p></div></article>)}</section><section className="contact-content"><form><h2>Send Us a Message</h2><p>Fill out the form and our team will get back to you.</p><div className="contact-fields"><label>Full Name<input placeholder="Enter your full name" /></label><label>Mobile Number<input placeholder="Enter your 10-digit mobile number" /></label></div><label>I am a<select><option>Select an option</option><option>Farmer</option><option>Procurement Centre</option></select></label><label>Subject<select><option>Select a subject</option><option>Appointment support</option><option>Payment support</option></select></label><label>Message<textarea placeholder="Type your message here..." /></label><button type="button">Send Message <ArrowRight size={16} /></button></form><div className="location-card"><h2>Our Location</h2><div className="map-placeholder"><MapPin size={30} /><strong>Department of Agriculture & Farmers Welfare</strong><span>Krishi Bhawan, New Delhi - 110001, India</span></div></div></section></main><PublicFooter /></div> }
function SectionHeading({ title }: { title: string }) { return <div className="audience-heading"><h2>{title}</h2><i /></div> }
function PublicHeader({ active }: { active: string }) { return <header className="audience-header"><a href="/" className="audience-brand"><Leaf size={29} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Procurement Platform</small></span></a><nav>{[['Home', '/'], ['About Us', '/about'], ['How It Works', '/how-it-works'], ['For Farmers', '/for-farmers'], ['For Centres', '/for-centres'], ['Features', '/features'], ['Contact Us', '/contact']].map(([label, path]) => <a className={label === active ? 'active' : ''} href={path} key={label}>{label}</a>)}</nav><a className="audience-book" href="/farmer/dashboard"><CalendarCheck size={15} /> Book a slot</a></header> }
function PublicFooter() { return <footer className="audience-footer"><div className="audience-brand"><Leaf size={25} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Procurement Platform</small></span></div><p>Know your turn. Know your status. Know your payment.</p><small>© 2026 Kisan Setu. All rights reserved.</small></footer> }
