import { useState } from 'react'
import { BarChart3, Banknote, CalendarDays, Check, CheckCircle2, FileCheck2, Globe2, Leaf, MapPin, Menu, MonitorCheck, Package, Plus, ReceiptText, Settings2, ShieldCheck, Ticket, Timer, UserRound, Users, X } from 'lucide-react'
import './HowItWorksPage.css'

type Icon = typeof Leaf
type Step = { title: string; text: string; icon: Icon }
type Role = { title: string; intro: string; icon: Icon; tone: string; labels: string[]; bullets: string[] }
const heroBadges: { label: string; icon: Icon }[] = [{ label: 'Easy and Simple', icon: CheckCircle2 }, { label: 'Transparent and Secure', icon: ShieldCheck }, { label: 'Real-time Updates', icon: Timer }, { label: 'Save Time and Effort', icon: Timer }]
const steps: Step[] = [
  { title: 'Book Slot', text: 'Farmer selects the nearest procurement centre and books a slot as per convenience.', icon: CalendarDays }, { title: 'Get Token', text: 'Farmer receives a unique token for the booked slot on SMS / App / WhatsApp.', icon: Ticket }, { title: 'Live Queue Tracking', text: 'Farmer can track the live queue status and estimated waiting time in real-time.', icon: Users }, { title: 'Procurement', text: 'Farmer visits the centre, quality check is done and produce is verified.', icon: Package }, { title: 'Secure Payment', text: "Payment is processed directly to farmer's bank account through secure system.", icon: Banknote }, { title: 'History & Records', text: 'Farmer can view complete history of procurement, payments anytime.', icon: ReceiptText },
]
const roles: Role[] = [
  { title: 'For Farmers', intro: 'Manage your produce, queue and payments easily.', icon: UserRound, tone: 'farmer', labels: ['Register / Login', 'Book Slot', 'Track Queue', 'Get Paid'], bullets: ['Book slots at nearby centre', 'Get real-time queue updates', 'Receive secure payments', 'Access complete records'] },
  { title: 'For Procurement Centres', intro: 'Streamline operations and manage procurement efficiently.', icon: MonitorCheck, tone: 'centre', labels: ['Manage Slots', 'Verify Produce', 'Update Queue', 'Generate Reports'], bullets: ['Manage daily slot availability', 'Verify and weigh produce', 'Update queue in real-time', 'Generate reports & analytics'] },
  { title: 'For Administrators', intro: 'Monitor, analyze and make data-driven decisions.', icon: Settings2, tone: 'admin', labels: ['Monitor Centres', 'Analytics', 'Manage Users', 'System Control'], bullets: ['Monitor all centres in real-time', 'View analytics & insights', 'Manage users and activities', 'Ensure transparency & security'] },
]
const benefits: [string, string, Icon][] = [
  ['Real-time Queue Management', 'Live tracking reduces waiting time and improves planning.', Timer], ['Transparent Process', 'Every step is recorded and visible to all.', MonitorCheck], ['Secure Payments', 'Direct bank transfers ensure safe and timely payments.', ShieldCheck], ['Data-driven Insights', 'Analytics helps in better planning and decisions.', BarChart3], ['Accessible Everywhere', 'Use via Web, Mobile App or WhatsApp.', Globe2], ['Multi-language Support', 'Available in multiple regional languages.', Globe2],
]
const journey: [string, string, Icon][] = [
  ['Farmer Books Slot', 'Chooses centre, date, and time.', CalendarDays], ['Receives Token', 'Gets confirmation with token number.', Ticket], ['Tracks Queue', 'Checks live status and estimated time.', Users], ['Visits Centre', 'Reaches centre at scheduled time.', MapPin], ['Quality Check', 'Produce is verified for quality.', FileCheck2], ['Payment Processed', 'Amount sent directly to bank account.', Banknote], ['View Records', 'All records available anytime.', ReceiptText],
]
const faq = ['How do I book a slot on Kisan Setu?', 'How is the queue managed?', 'How will I receive my token?', 'How will I receive payment?', 'Can I reschedule or cancel my slot?', 'Is my data safe and secure?']

export default function HowItWorksPage() {
  return <div className="works-page"><WorksHeader /><main><section className="works-hero"><div className="works-hero-image" /><div className="works-hero-overlay" /><div className="works-hero-copy"><h1>How Kisan Setu Works</h1><h2>Simple Steps, Smarter Procurement</h2><p>Kisan Setu simplifies the entire procurement journey for farmers, procurement centres and administrators through technology, transparency and trust.</p><div className="hero-badges">{heroBadges.map(({ label, icon: BadgeIcon }) => <span key={label}><BadgeIcon size={14} />{label}</span>)}</div></div></section><section className="works-section process-section"><SectionHeading title="The Kisan Setu Process – Step by Step" /><div className="process-grid">{steps.map(({ title, text, icon: StepIcon }, index) => <article className="process-card" key={title}><b>{index + 1}</b><span><StepIcon size={23} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="works-section roles-section"><SectionHeading title="Workflows for Every Role" /><div className="roles-grid">{roles.map(({ title, intro, icon: RoleIcon, tone, labels, bullets }) => <article className={`role-card ${tone}`} key={title}><header><span><RoleIcon size={19} /></span><div><h3>{title}</h3><p>{intro}</p></div></header><div className="role-flow">{labels.map((label, index) => <div key={label}><span>{index + 1}</span><small>{label}</small></div>)}</div><ul>{bullets.map((bullet) => <li key={bullet}><Check size={14} />{bullet}</li>)}</ul></article>)}</div></section><section className="works-section benefits-section"><SectionHeading title="What Makes It Work Better?" /><div className="benefits-grid">{benefits.map(([title, text, BenefitIcon]) => <article key={String(title)}><span><BenefitIcon size={17} /></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section><section className="works-section journey-section"><SectionHeading title="One Platform. One Journey. Many Benefits." /><div className="journey-grid">{journey.map(([title, text, JourneyIcon]) => <div key={String(title)}><span><JourneyIcon size={18} /></span><h3>{title}</h3><p>{text}</p></div>)}</div></section><section className="works-section faq-section"><SectionHeading title="Got Questions? We've Got Answers." /><div className="faq-grid">{faq.map((question) => <button key={question}>{question}<Plus size={15} /></button>)}</div></section></main><WorksFooter /></div>
}
function SectionHeading({ title }: { title: string }) { return <div className="works-heading"><h2>{title}</h2><i /></div> }
function WorksHeader() { const [menuOpen, setMenuOpen] = useState(false); return <header className="works-header"><a href="/" className="works-brand"><Leaf size={29} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Procurement Platform</small></span></a><nav className={menuOpen ? 'mobile-open' : ''}><a href="/" onClick={() => setMenuOpen(false)}>Home</a><a href="/about" onClick={() => setMenuOpen(false)}>About Us</a><a className="active" href="/how-it-works" onClick={() => setMenuOpen(false)}>How It Works</a><a href="/for-farmers" onClick={() => setMenuOpen(false)}>For Farmers</a><a href="/for-centres" onClick={() => setMenuOpen(false)}>For Centres</a><a href="/features" onClick={() => setMenuOpen(false)}>Features</a><a href="/contact" onClick={() => setMenuOpen(false)}>Contact Us</a><button className="works-mobile-close" aria-label="Close navigation" onClick={() => setMenuOpen(false)}><X size={20} /></button></nav><a className="works-cta" href="/farmer/dashboard"><CalendarDays size={15} /> Book a slot</a><button className="works-menu" aria-label="Open navigation" onClick={() => setMenuOpen(true)}><Menu size={20} /></button></header> }
function WorksFooter() { return <footer className="works-footer"><div className="works-brand"><Leaf size={25} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Procurement Platform</small></span></div><p>Know your turn. Know your status. Know your payment.</p><div><strong>Need help?</strong><p>1800-123-4567</p><p>support@kisansetu.gov.in</p></div><small>© 2026 Kisan Setu. All rights reserved.</small></footer> }
