import { useState } from 'react'
import type { FormEvent } from 'react'
import { ArrowRight, Eye, EyeOff, Leaf, LockKeyhole, Phone, ReceiptText, ShieldCheck, Smartphone } from 'lucide-react'
import './LoginPage.css'

export default function LoginPage() {
  const [showPassword, setShowPassword] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  return <main className="login-page"><section className="login-hero"><div className="login-hero-photo" /><div className="login-hero-scrim" /><div className="login-hero-content"><a href="/" className="login-brand"><Leaf size={31} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Kisan ka Saathi, Har Kadam Saath</small></span></a><div className="login-hero-copy"><h1>Aapka Faslon ka<br /><em>Bharosemand Saathi</em></h1><p>Connect with your nearest center, book your slot, and get fair payment.</p></div></div></section><section className="login-card-wrap"><div className="login-card"><div className="login-mark"><Leaf size={29} /></div><h2>Welcome Back, Farmer!</h2><p className="login-subtitle">Login to your Kisan Setu account</p><form onSubmit={handleSubmit}><label htmlFor="mobile">Mobile Number</label><div className="login-input"><Phone size={19} /><span>+91</span><input id="mobile" type="tel" placeholder="Enter your mobile number" required /></div><div className="password-label"><label htmlFor="password">Password</label><a href="#forgot">Forgot Password?</a></div><div className="login-input"><LockKeyhole size={19} /><input id="password" type={showPassword ? 'text' : 'password'} placeholder="Enter your password" required /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={20} /> : <Eye size={20} />}</button></div><button className="login-submit" type="submit">Login <ArrowRight size={20} /></button>{submitted && <p className="login-message">Demo mode: credentials are not connected to a backend yet.</p>}</form><div className="login-divider"><span />OR<span /></div><button className="otp-button" type="button"><Smartphone size={19} /> Login with OTP</button><p className="register-copy">New to Kisan Setu? <a href="/farmer/dashboard">Register Now</a></p></div><div className="trust-banner"><div><span><ShieldCheck size={20} /></span><section><strong>Secure & Trusted</strong><small>Trusted by thousands across India</small></section></div><i /><div><span><ReceiptText size={20} /></span><section><strong>Transparent Process</strong><small>Clear pricing, no hidden fees</small></section></div></div><footer className="login-footer"><div><a href="#privacy">Privacy Policy</a><b>•</b><a href="#terms">Terms of Use</a><b>•</b><span>◉ English</span></div><small>© 2026 Kisan Setu. All rights reserved.</small></footer></section></main>
}
