import { ArrowRight, CalendarCheck, CheckCircle2, CircleHelp, FileCheck2, Leaf, Mail, MapPin, Phone, ShieldCheck, Sprout, Users, WalletCards } from 'lucide-react'
import './PublicPage.css'
import AboutPage from './AboutPage'
import HowItWorksPage from './HowItWorksPage'
import AudiencePage from './AudiencePage'

type Page = { title: string; intro: string; icon: typeof Leaf; points: { title: string; text: string; icon: typeof Leaf }[] }
const pages: Record<string, Page> = {
  '/about': { title: 'About Kisan Setu', intro: 'A trusted digital bridge between farmers and transparent agricultural procurement.', icon: Leaf, points: [{ title: 'Built for farmers', text: 'Simple tools help farmers plan visits, track progress, and receive timely payments.', icon: Users }, { title: 'Designed for trust', text: 'Every step from appointment to payment is clear, traceable, and easy to understand.', icon: ShieldCheck }, { title: 'Ready for scale', text: 'A connected platform supports procurement centres and administrators across India.', icon: Sprout }] },
  '/features': { title: 'Everything you need for better procurement', intro: 'Kisan Setu brings the entire procurement journey into one calm, predictable experience.', icon: Sprout, points: [{ title: 'Book slots in advance', text: 'Choose a centre, crop, quantity, date, and available time slot.', icon: CalendarCheck }, { title: 'See your live queue', text: 'Know your token, farmers ahead, active counters, and estimated waiting time.', icon: CircleHelp }, { title: 'Track payment status', text: 'Follow weighment, quality, procurement, approval, and payment in one place.', icon: WalletCards }] },
  '/how-it-works': { title: 'How Kisan Setu works', intro: 'From your first booking to your final receipt, each step is visible and connected.', icon: FileCheck2, points: [{ title: '1. Discover and book', text: 'Find a nearby centre and reserve a slot that fits your schedule.', icon: MapPin }, { title: '2. Check in and track', text: 'Receive your token, check in at the centre, and follow the live queue.', icon: CheckCircle2 }, { title: '3. Procure and get paid', text: 'Weighment, quality checks, procurement, and payment are recorded transparently.', icon: WalletCards }] },
  '/for-farmers': { title: 'A simpler day for every farmer', intro: 'Spend less time waiting and more time planning your farm.', icon: Users, points: [{ title: 'Plan your visit', text: 'Reserve an appointment before you travel to the procurement centre.', icon: CalendarCheck }, { title: 'Know your turn', text: 'Stay informed with tokens, queue progress, and reminders.', icon: CircleHelp }, { title: 'Know your payment', text: 'See quantity, rate, deductions, and payment status clearly.', icon: WalletCards }] },
  '/for-centres': { title: 'A smarter way to run your centre', intro: 'Give your team the tools to manage daily operations with clarity and confidence.', icon: Sprout, points: [{ title: 'Organise queues', text: 'Manage tokens, counters, check-ins, and service flow from one view.', icon: Users }, { title: 'Record every stage', text: 'Capture weighment, quality, procurement, and payment information accurately.', icon: FileCheck2 }, { title: 'Make better decisions', text: 'Use operational reports and live signals to plan staffing and capacity.', icon: ShieldCheck }] },
  '/contact': { title: 'We are here to help', intro: 'Reach the Kisan Setu support team for questions about appointments, queues, procurement, or payments.', icon: Mail, points: [{ title: 'Call support', text: '1800-123-4567, Monday to Saturday, 8:00 AM to 8:00 PM.', icon: Phone }, { title: 'Email us', text: 'support@kisansetu.gov.in and we will get back to you.', icon: Mail }, { title: 'Visit the office', text: 'Krishi Bhawan, New Delhi - 110001.', icon: MapPin }] },
}
  const publicNav = [
    { label: 'Home', path: '/' }, { label: 'About Us', path: '/about' }, { label: 'How It Works', path: '/how-it-works' },
    { label: 'For Farmers', path: '/for-farmers' }, { label: 'For Centres', path: '/for-centres' }, { label: 'Features', path: '/features' }, { label: 'Contact Us', path: '/contact' },
  ]

export default function PublicPage({ path }: { path: string }) {
  if (path === '/about') return <AboutPage />
  if (path === '/how-it-works') return <HowItWorksPage />
  if (['/for-farmers', '/for-centres', '/features', '/contact'].includes(path)) return <AudiencePage path={path} />
  const page = pages[path] ?? pages['/about']
  const PageIcon = page.icon
    return <div className="public-page"><header className="public-header"><a href="/" className="public-brand"><Leaf size={29} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Procurement Platform</small></span></a><nav>{publicNav.map(({ path: route, label }) => <a key={route} className={route === path ? 'active' : ''} href={route}>{label}</a>)}</nav><a className="public-cta" href="/farmer/dashboard"><CalendarCheck size={16} /> Book a slot</a></header><main><section className="public-hero"><div className="public-hero-copy"><span className="public-kicker"><PageIcon size={15} /> KISAN SETU</span><h1>{page.title}</h1><p>{page.intro}</p><a className="public-primary" href={path === '/contact' ? 'mailto:support@kisansetu.gov.in' : '/farmer/dashboard'}>{path === '/contact' ? 'Contact support' : 'Get started'} <ArrowRight size={17} /></a></div><div className="public-orbit"><div className="orbit-core"><PageIcon size={42} /></div><span>Simple</span><span>Transparent</span><span>Connected</span></div></section><section className="public-points"><p className="public-eyebrow">The Kisan Setu difference</p><h2>Tools that make every step clearer</h2><div className="public-point-grid">{page.points.map(({ title, text, icon: PointIcon }) => <article key={title}><span><PointIcon size={21} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section></main><footer className="public-footer"><div><div className="public-brand"><Leaf size={25} fill="currentColor" /><span><strong>Kisan Setu</strong><small>Procurement Platform</small></span></div><p>Know your turn. Know your status. Know your payment.</p></div><div><strong>Need help?</strong><p><Phone size={13} /> 1800-123-4567</p><p><Mail size={13} /> support@kisansetu.gov.in</p></div><small className="public-copyright">© 2024 Kisan Setu. All rights reserved.</small></footer></div>
}
